"""split client and company

Revision ID: 03696b1afffc
Revises: babed21ff739
Create Date: 2026-06-12 10:41:21.423282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03696b1afffc'
down_revision: Union[str, Sequence[str], None] = 'babed21ff739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('tax_number', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_companies_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_companies_company_code'), ['company_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_companies_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_companies_id'), ['id'], unique=False)

    with op.batch_alter_table('client_consultants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_client_consultants_client_id'))
        batch_op.create_index(batch_op.f('ix_client_consultants_company_id'), ['company_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('client_consultants_client_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'client_companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('client_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_client_documents_client_id'))
        batch_op.create_index(batch_op.f('ix_client_documents_company_id'), ['company_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('client_documents_client_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'client_companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_client_code'))
        batch_op.drop_index(batch_op.f('ix_clients_company_name'))
        batch_op.drop_column('client_code')
        batch_op.drop_column('company_name')
        batch_op.drop_column('tax_number')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('address')
        batch_op.drop_column('industry')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_conversations_client_id'))
        batch_op.create_index(batch_op.f('ix_conversations_company_id'), ['company_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('conversations_client_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'client_companies', ['company_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'client_companies', ['company_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversations_client_id_fkey'), 'clients', ['client_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_conversations_company_id'))
        batch_op.create_index(batch_op.f('ix_conversations_client_id'), ['client_id'], unique=False)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tax_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('client_code', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_client_code'), ['client_code'], unique=True)

    with op.batch_alter_table('client_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('client_documents_client_id_fkey'), 'clients', ['client_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_client_documents_company_id'))
        batch_op.create_index(batch_op.f('ix_client_documents_client_id'), ['client_id'], unique=False)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('client_consultants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('client_consultants_client_id_fkey'), 'clients', ['client_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_client_consultants_company_id'))
        batch_op.create_index(batch_op.f('ix_client_consultants_client_id'), ['client_id'], unique=False)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('client_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_companies_id'))
        batch_op.drop_index(batch_op.f('ix_client_companies_company_name'))
        batch_op.drop_index(batch_op.f('ix_client_companies_company_code'))
        batch_op.drop_index(batch_op.f('ix_client_companies_client_id'))

    op.drop_table('client_companies')
    # ### end Alembic commands ###
