"""add leave columns to payroll

Revision ID: 26e1c71c23bf
Revises: ca7e76726602
Create Date: 2026-06-11 14:15:56.299226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e1c71c23bf'
down_revision: Union[str, Sequence[str], None] = 'ca7e76726602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_leave_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sick_leave_days', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unpaid_leave_days', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_column('unpaid_leave_days')
        batch_op.drop_column('sick_leave_days')
        batch_op.drop_column('annual_leave_days')

    # ### end Alembic commands ###
