"""Add Timesheet models

Revision ID: 3c15ebcf1dac
Revises: 69627307cdcc
Create Date: 2026-06-07 14:35:20.721937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c15ebcf1dac'
down_revision: Union[str, Sequence[str], None] = '69627307cdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('project_code', sa.String(), nullable=True),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_code'), ['project_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_project_name'), ['project_name'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)

    op.create_table('timesheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('week_end', sa.Date(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='timesheetstatus'), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timesheets_id'), ['id'], unique=False)

    op.create_table('timesheet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timesheet_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('break_duration', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['timesheet_id'], ['timesheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timesheet_entries_id'), ['id'], unique=False)

    with op.batch_alter_table('asset_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_assignments_id'), ['id'], unique=False)

    with op.batch_alter_table('asset_history', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_asset_history_id'), ['id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('assets_asset_tag_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('assets_serial_number_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_assets_asset_tag'), ['asset_tag'], unique=True)
        batch_op.create_index(batch_op.f('ix_assets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_serial_number'), ['serial_number'], unique=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_attendance_date'), ['attendance_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_id'), ['id'], unique=False)

    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_attendance_corrections_id'), ['id'], unique=False)

    with op.batch_alter_table('attendance_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_settings_id'), ['id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_employee_id_custom'), ['employee_id_custom'], unique=True)

    with op.batch_alter_table('leave_balance_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balance_audit_id'), ['id'], unique=False)

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_balances_id'), ['id'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('payroll_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_audit_logs_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_audit_logs_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balances_id'))

    with op.batch_alter_table('leave_balance_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_balance_audit_id'))

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_employee_id_custom'))

    with op.batch_alter_table('attendance_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_settings_id'))

    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_corrections_id'))
        batch_op.alter_column('reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_attendance_date'))

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_serial_number'))
        batch_op.drop_index(batch_op.f('ix_assets_id'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_tag'))
        batch_op.create_unique_constraint(batch_op.f('assets_serial_number_key'), ['serial_number'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('assets_asset_tag_key'), ['asset_tag'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('asset_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_history_id'))
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('asset_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_assignments_id'))

    with op.batch_alter_table('timesheet_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timesheet_entries_id'))

    op.drop_table('timesheet_entries')
    with op.batch_alter_table('timesheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timesheets_id'))

    op.drop_table('timesheets')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_project_name'))
        batch_op.drop_index(batch_op.f('ix_projects_project_code'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    # ### end Alembic commands ###
