"""add_maternity_leave_days

Revision ID: 59086388a6a9
Revises: a046f5c70567
Create Date: 2026-06-24 14:28:25.174824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59086388a6a9'
down_revision: Union[str, Sequence[str], None] = 'a046f5c70567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maternity_leave_days', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_column('maternity_leave_days')

    # ### end Alembic commands ###
