"""Add secure payslip fields

Revision ID: 69627307cdcc
Revises: 0be934ca2528
Create Date: 2026-06-06 14:18:30.973782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69627307cdcc'
down_revision: Union[str, Sequence[str], None] = '0be934ca2528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_id'], ['payrolls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_audit_logs_id'), 'payroll_audit_logs', ['id'], unique=False)
    op.add_column('payrolls', sa.Column('encrypted_pdf_password', sa.String(), nullable=True))
    op.add_column('payrolls', sa.Column('password_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payrolls', sa.Column('download_count', sa.Integer(), nullable=True))
    op.add_column('payrolls', sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payrolls', sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payrolls', sa.Column('generated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payrolls', 'users', ['generated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payrolls', type_='foreignkey')
    op.drop_column('payrolls', 'generated_by')
    op.drop_column('payrolls', 'generated_at')
    op.drop_column('payrolls', 'last_downloaded_at')
    op.drop_column('payrolls', 'download_count')
    op.drop_column('payrolls', 'password_sent_at')
    op.drop_column('payrolls', 'encrypted_pdf_password')
    op.drop_index(op.f('ix_payroll_audit_logs_id'), table_name='payroll_audit_logs')
    op.drop_table('payroll_audit_logs')
    # ### end Alembic commands ###
