"""add public_holidays

Revision ID: ca7e76726602
Revises: 3c15ebcf1dac
Create Date: 2026-06-11 13:30:13.192871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca7e76726602'
down_revision: Union[str, Sequence[str], None] = '3c15ebcf1dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balance_audit', schema=None) as batch_op:
        batch_op.alter_column('old_annual_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('new_annual_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('old_sick_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('new_sick_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('public_holidays', schema=None) as batch_op:
        batch_op.alter_column('holiday_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('holiday_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('holiday_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('public_holidays_holiday_date_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_public_holidays_holiday_date'), ['holiday_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_holidays_holiday_name'), ['holiday_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_holidays_id'), ['id'], unique=False)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_holidays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_public_holidays_id'))
        batch_op.drop_index(batch_op.f('ix_public_holidays_holiday_name'))
        batch_op.drop_index(batch_op.f('ix_public_holidays_holiday_date'))
        batch_op.create_unique_constraint(batch_op.f('public_holidays_holiday_date_key'), ['holiday_date'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('holiday_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('holiday_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('holiday_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('leave_balance_audit', schema=None) as batch_op:
        batch_op.alter_column('new_sick_balance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('old_sick_balance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('new_annual_balance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('old_annual_balance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
